<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-QS6OB0P6" name="dataDrivenTesting.TC001_POST_Request_DDT" tests="5" failures="1" timestamp="7 Aug 2022 14:26:28 GMT" time="7.156" errors="0">
  <testcase name="postNewEmployee" time="1.016" classname="dataDrivenTesting.TC001_POST_Request_DDT"/>
  <testcase name="postNewEmployee" time="1.031" classname="dataDrivenTesting.TC001_POST_Request_DDT"/>
  <testcase name="postNewEmployee" time="1.293" classname="dataDrivenTesting.TC001_POST_Request_DDT"/>
  <testcase name="postNewEmployee" time="1.043" classname="dataDrivenTesting.TC001_POST_Request_DDT">
    <failure type="junit.framework.AssertionFailedError" message="expected:&lt;429&gt; but was:&lt;200&gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<429> but was:<200>
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:199)
	at junit.framework.Assert.assertEquals(Assert.java:205)
	at dataDrivenTesting.TC001_POST_Request_DDT.postNewEmployee(TC001_POST_Request_DDT.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- postNewEmployee -->
  <testcase name="postNewEmployee" time="2.773" classname="dataDrivenTesting.TC001_POST_Request_DDT"/>
</testsuite> <!-- dataDrivenTesting.TC001_POST_Request_DDT -->
